language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit --coverage-text

notifications:
  email:
    recipients:
      - steve.west@veinteractive.com

